spring.application.name=Scraping

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=tempdb;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update

# JPA Settings, It shows our query so we comment this

#spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Format SQL queries
#spring.jpa.properties.hibernate.format_sql=true
#
## Show SQL with parameters
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE